DECLARE @TRH1 AS DATETIME='{TARIH1}'
DECLARE @TRH2 AS DATETIME='{TARIH2}'
DECLARE @URUNGRUBU AS NVARCHAR(MAX)='{URUNGRUBU}'
DECLARE @SUBEADI AS NVARCHAR(100)='{SUBEADI}'
DECLARE @SATISTIPI AS NVARCHAR(100)='{SATISTIPI}'
DECLARE @URUNADI AS NVARCHAR(100)='{URUNADI}'


SELECT T.ÜrünGrubu,SUM(Miktar) as Miktar FROM (
SELECT 
ProductGroup AS ÜrünGrubu,
SUM(Quantity) as Miktar,NEWID() as TEKIL
 FROM [dbo].[Bill] AS BAS
WHERE Date>=@TRH1  AND Date<=@TRH2 #URUNGRUBUWHERE# #SUBEADIWHERE# #SATISTIPIWHERE# #URUNADIWHERE#
AND KOD1 LIKE '%ÝÇECEK%'
group by
AGIRLIK,
ProductGroup
UNION
SELECT 
HAR.ProductGroup AS ÜrünGrubu,
SUM(MIKTAR*ANAMIKTAR) as Miktar,NEWID() as TEKIL
 FROM [dbo].TBLBILLOPTIONS AS  HAR
 LEFT JOIN [Bill] AS BAS  ON BAS.Id=HAR.BIND
WHERE TARIH>=@TRH1  AND TARIH<=@TRH2 #URUNGRUBUWHERE2# #SUBEADIWHERE# #URUNADIWHERE2# #SATISTIPIWHERE2#
AND VEGAKOD1 LIKE '%ÝÇECEK%'
group by
HAR.ProductGroup


) AS T
group by
t.ÜrünGrubu