DECLARE @TRH1 AS DATETIME='{TARIH1}'
DECLARE @TRH2 AS DATETIME='{TARIH2}'
DECLARE @URUNGRUBU AS NVARCHAR(MAX)='{URUNGRUBU}'
DECLARE @SUBEADI AS NVARCHAR(100)='{SUBEADI}'
DECLARE @SATISTIPI AS NVARCHAR(100)='{SATISTIPI}'
DECLARE @URUNADI AS NVARCHAR(100)='{URUNADI}'

SELECT T.SUBEADI,T.ÜrünAdi,SUM(T.Miktar) AS Miktar FROM (
SELECT 
NEWID() AS TEKIL,
SUBEADI,
ProductName AS ÜrünAdi,
SUM(Quantity) as Miktar
 FROM [dbo].[Bill] AS BAS
WHERE Date>=@TRH1  AND Date<=@TRH2 #URUNGRUBUWHERE# #SUBEADIWHERE# #SATISTIPIWHERE# #URUNADIWHERE#
AND KOD1 LIKE '%ÝÇECEK%'
group by
SUBEADI,
ProductName

UNION
SELECT 
NEWID() AS TEKIL,
SUBEADI,
URUNADI AS ÜrünAdi,
SUM(MIKTAR*ANAMIKTAR) as Miktar
 FROM [dbo].TBLBILLOPTIONS AS  HAR
 LEFT JOIN [Bill] AS BAS  ON BAS.Id=HAR.BIND
WHERE TARIH>=@TRH1  AND TARIH<=@TRH2 #URUNGRUBUWHERE2# #SUBEADIWHERE# #SATISTIPIWHERE# #URUNADIWHERE2#
AND VEGAKOD1 LIKE '%ÝÇECEK%'
group by
SUBEADI,
URUNADI) AS T
group by
T.SUBEADI,T.ÜrünAdi