DECLARE @TRH1 AS DATETIME='{TARIH1}'
DECLARE @TRH2 AS DATETIME='{TARIH2}'
DECLARE @URUNGRUBU AS NVARCHAR(MAX)='{URUNGRUBU}'
DECLARE @SUBEADI AS NVARCHAR(100)='{SUBEADI}'
DECLARE @SATISTIPI AS NVARCHAR(100)='{SATISTIPI}'
DECLARE @URUNADI AS NVARCHAR(100)='{URUNADI}'

select 
COUNT(DISTINCT(SUBEADI)) AS KS,
t.ProductName,sum(Miktar) AS MIKTAR  from (
SELECT 
NEWID() AS TEKIL,
Productname,
SUBEADI AS SUBEADI,
SUM(Quantity) as Miktar
 FROM [dbo].[Bill] AS BAS
WHERE Date>=@TRH1  AND Date<=@TRH2 #URUNGRUBUWHERE# #SUBEADIWHERE# #SATISTIPIWHERE# #URUNADIWHERE#
AND KOD1 LIKE '%ÝÇECEK%' 
group by
SUBEADI,
Productname

UNION
SELECT 
NEWID() AS TEKIL,
URUNADI,
SUBEADI AS SUBEADI,
SUM(MIKTAR*ANAMIKTAR) as Miktar
 FROM [dbo].TBLBILLOPTIONS AS  HAR
 LEFT JOIN [Bill] AS BAS  ON BAS.Id=HAR.BIND
WHERE TARIH>=@TRH1  AND TARIH<=@TRH2 #URUNGRUBUWHERE2# #SUBEADIWHERE# #SATISTIPIWHERE# #URUNADIWHERE2#
AND VEGAKOD1 LIKE '%ÝÇECEK%'
group by
SUBEADI,
URUNADI) as t
GROUP BY
ProductName