DECLARE @TRH1 AS DATETIME='{TARIH1}'
DECLARE @TRH2 AS DATETIME='{TARIH2}'
DECLARE @SUBEADI AS NVARCHAR(100)='{SUBEADI}'
SELECT 
SUBEADI,
CAST(AGIRLIK*1000 AS INT) AS AGIRLIK,

SUM(quantity) as Miktar,
SUM(quantity*AGIRLIK) as ToplamKg
 FROM [dbo].[Bill]
WHERE Date>=@TRH1  AND Date<=@TRH2  #SUBEADIWHERE#
AND KOD1 LIKE '%ET D%' 
group by
AGIRLIK,
SUBEADI
