/*Ürün  Adi*/
DECLARE @TRH1 AS DATETIME='{TARIH1}'
DECLARE @TRH2 AS DATETIME='{TARIH2}'
DECLARE @KOD1 NVARCHAR(100)='{KOD1}'
DECLARE @ProductGroup AS NVARCHAR(100)='{ProductGroup}'
DECLARE @URUNADI AS NVARCHAR(100)='{URUNADI}'
DECLARE @SUBEADI AS NVARCHAR(100)='{SUBEADI}'
SELECT 
ProductName,
SUM(Quantity) as Miktar,Sum(Quantity*Price) as Tutar
 FROM [dbo].[Bill]
WHERE Date>=@TRH1  AND Date<=@TRH2 #KOD1WHERE# #ProductGroupWHERE# #URUNADIWHERE# #BELÝRLÝSAATLER# #SUBEADIWHERE#
GROUP BY ProductName