      
declare @par1 nvarchar(20) = '{TARIH1}';
declare @par2 nvarchar(20) = '{TARIH2}';
declare @Sube nvarchar(100) = '{SubeAdi}';
declare @Sube2 nvarchar(100) = '{SUBE2}';
declare @Kasa nvarchar(100) = '{KASAKODU}';
Declare @par3 nvarchar(36) = '{ID}';

		WITH SATISRAPORU AS (
		SELECT

			(SELECT CASE WHEN IADE=1 THEN SUM(TUTAR)*-1 ELSE SUM(TUTAR) END AS TUTAR  FROM TBLSPOSSATISTAHSILAT T WITH(NOLOCK) WHERE T.SATISBASLIKIND=BAS.IND  AND BAS.IND=@par3 AND T.ISLEMTIPI=1 GROUP BY IADE) Cash,
			(SELECT CASE WHEN IADE=1 THEN SUM(TUTAR)*-1 ELSE SUM(TUTAR) END AS TUTAR  FROM TBLSPOSSATISTAHSILAT T WITH(NOLOCK) WHERE T.SATISBASLIKIND=BAS.IND  AND BAS.IND=@par3 AND T.ISLEMTIPI=2 GROUP BY IADE) Credit,
			(SELECT CASE WHEN IADE=1 THEN SUM(TUTAR)*-1 ELSE SUM(TUTAR) END AS TUTAR  FROM TBLSPOSSATISTAHSILAT T WITH(NOLOCK) WHERE T.SATISBASLIKIND=BAS.IND  AND BAS.IND=@par3 AND T.ISLEMTIPI=3 GROUP BY IADE) Ticket,
			(SELECT CASE WHEN IADE=1 THEN SUM(TUTAR)*-1 ELSE SUM(TUTAR) END AS TUTAR  FROM TBLSPOSSATISTAHSILAT T WITH(NOLOCK) WHERE T.SATISBASLIKIND=BAS.IND  AND BAS.IND=@par3 AND T.ISLEMTIPI=4 GROUP BY IADE) Debit,
			(SELECT CASE WHEN IADE=1 THEN SUM(TUTAR)*-1 ELSE SUM(TUTAR) END AS TUTAR  FROM TBLSPOSSATISTAHSILAT T WITH(NOLOCK) WHERE T.SATISBASLIKIND=BAS.IND  AND BAS.IND=@par3 AND T.ISLEMTIPI=99 GROUP BY IADE) OnlinePayment,
			(SELECT CASE WHEN IADE=1 THEN SUM(TUTAR)*-1 ELSE SUM(TUTAR) END AS TUTAR  FROM TBLSPOSSATISTAHSILAT T WITH(NOLOCK) WHERE T.SATISBASLIKIND=BAS.IND  AND BAS.IND=@par3 AND T.ISLEMTIPI=88 GROUP BY IADE) OnlineDiscount,
			(SELECT top 1 t.OLUSTURMATARIHI TARIH  FROM TBLSPOSSATISTAHSILAT T WITH(NOLOCK) WHERE T.SATISBASLIKIND=BAS.IND  AND BAS.IND=@par3 ) OdemeZamani,
			(SELECT TOP 1 ISNULL(KODU,'')+'/'+ISNULL(ADI,'') From TBLSPOSCARILER WITH(NOLOCK)  WHERE IND=BAS.CARIIND AND BAS.IND=@par3 ) AS CustomerName,

			BAS.TARIH,
			BAS.OLUSTURMATARIHI,
			STOKIND,
			STOKKODU,
			STK.OZELKOD1,
			STOKADI,
			BIRIM,
			BAS.SUBEIND,
			HAR.SONDEGISTIRME SIPARISTARIHI,
			CAST(HAR.ACIKLAMA AS NVARCHAR(50)) ACIKLAMA,
			ISNULL(K.KODU,'')+'/'+ISNULL(K.ADI,'') SIPARISIALAN,
			CASE WHEN BAS.IADE=0 THEN (HAR.MIKTAR) ELSE 0 END AS SATIS_MIKTARI,
			CASE WHEN BAS.IADE<>0 THEN (HAR.MIKTAR) ELSE 0 END AS IADE_MIKTARI,
			CASE WHEN BAS.IADE=0 THEN (HAR.MIKTAR*HAR.FIYAT) ELSE 0 END AS SATIS_TUTARI_TL,
			CASE WHEN BAS.IADE<>0 THEN (HAR.MIKTAR*HAR.FIYAT) ELSE 0 END AS IADE_TUTARI_TL,
			CASE WHEN BAS.IADE=0 THEN (HAR.ISKTUTARI) ELSE 0 END AS SATIS_ISKTUTARI_TL,
			CASE WHEN BAS.IADE<>0 THEN (HAR.ISKTUTARI) ELSE 0 END AS IADE_ISKTUTARI_TL
		 FROM TBLSPOSSATISHAREKET AS HAR WITH(NOLOCK)
		 JOIN TBLSPOSSATISBASLIK AS BAS WITH(NOLOCK) ON BAS.IND=HAR.BASLIKIND
		 LEFT JOIN TBLSPOSSTOKLAR AS STK WITH(NOLOCK) ON STK.IND=HAR.STOKIND
		 LEFT JOIN TBLSPOSKULLANICILAR K WITH(NOLOCK)  ON  K.IND=BAS.KULLANICIIND
		 WHERE ISNULL(BAS.IsDeleted,0)=0 AND ISNULL(HAR.IsDeleted,0)=0 AND ISNULL(BAS.BEKLEYENFIS,0)=0
		 AND BAS.IND=@par3 )



		SELECT 
		ISNULL(Cash,0) Cash, 
		ISNULL(Credit,0) Credit,
		ISNULL(Ticket,0) Ticket,
		ISNULL(Debit,0) Debit,
		ISNULL(OnlinePayment,0) OnlinePayment,
		ISNULL(OnlineDiscount,0) OnlineDiscount,
		OdemeZamani,
		ISNULL(CustomerName,'') CustomerName,
		SIPARISTARIHI,
		SIPARISIALAN,		
		STOKADI  ProductName,
		SUM(SATIS_MIKTARI)-SUM(IADE_MIKTARI) AS MIKTAR,
		(SUM(SATIS_TUTARI_TL) -SUM(IADE_TUTARI_TL))-(SUM(SATIS_ISKTUTARI_TL)-SUM(IADE_ISKTUTARI_TL)) TUTAR,
		ISNULL(ACIKLAMA,'') ACIKLAMA

		FROM SATISRAPORU H WITH(NOLOCK) 

		GROUP BY 
		SIPARISTARIHI,
		SIPARISIALAN,
		STOKADI,
		ACIKLAMA,
		Cash,
		Credit,
		Ticket,
		Debit,
		OnlinePayment,
		OnlineDiscount,
		OdemeZamani,
		CustomerName
