DECLARE @Sube nvarchar(100) = 'SubeAdi';

DECLARE @par1 nvarchar(20) = '{TARIH1}';

DECLARE @par2 nvarchar(20) = '{TARIH2}';


SELECT @Sube AS Sube,

  (SELECT TOP 1 SUBEADI
   FROM TBLFASTERKASALAR
   WHERE SUBENO=TBLFASTERBEKLEYENBASLIK.SUBEIND) AS Sube1,

  (SELECT KASAADI
   FROM TBLFASTERKASALAR
   WHERE KASANO=TBLFASTERBEKLEYENBASLIK.KASAIND) AS Kasa,

  (SELECT IND
   FROM TBLFASTERKASALAR
   WHERE KASANO=TBLFASTERBEKLEYENBASLIK.KASAIND) AS ID,
       FIRMAKODU TableNumber,
       min(ISLEMTARIHI) AS Date,
       COUNT(FIRMAKODU) AS TOPLAM_MASA,
       sum(TUTAR) AS TUTAR,
       BASLIKIND
FROM TBLFASTERBEKLEYENBASLIK
WHERE ISLEMTARIHI>=@par1
  AND ISLEMTARIHI<=@par2
GROUP BY SUBEIND,
         KASAIND,
         FIRMAKODU,
         BASLIKIND
HAVING COUNT (FIRMAKODU) > 0 --select
--@Sube as Sube,
--(SELECT TOP 1 SUBEADI FROM TBLFASTERKASALAR WHERE SUBENO=TBLFASTERBEKLEYENBASLIK.SUBEIND) AS Sube1,
--(SELECT KASAADI FROM TBLFASTERKASALAR WHERE KASANO=TBLFASTERBEKLEYENBASLIK.KASAIND) AS Kasa,
--FIRMAKODU TableNumber,min(ISLEMTARIHI) as Date, COUNT(FIRMAKODU) as TableNumber, sum(TUTAR)  as TUTAR
--from TBLFASTERBEKLEYENBASLIK   where  ISLEMTARIHI>=@par1 AND
--ISLEMTARIHI<=@par2
--group by SUBEIND,KASAIND,FIRMAKODU
--having Count (FIRMAKODU) > 0