
declare @Sube nvarchar(100) = '{SUBE}';
declare @Trh1 nvarchar(20) = '{TARIH1}';
declare @Trh2 nvarchar(20) = '{TARIH2}';


SELECT
T.SUBE1,
T.KASA,
T.PERSONEL,
SUM(ISNULL(MIKTAR,0)) AS MIKTAR,
SUM(ISNULL(TUTAR,0)) AS TUTAR
FROM (
( SELECT
(SELECT TOP 1 SUBEADI FROM TBLFASTERKASALAR WHERE SUBENO=FSB.SUBEIND) AS Sube1,
(SELECT KASAADI FROM TBLFASTERKASALAR WHERE KASANO=FSB.KASAIND) AS Kasa,
SUM(FSH.MIKTAR) AS MIKTAR,
SUM((((MIKTAR*SATISFIYATI) * (100-ISNULL(FSH.ISK1,0))/100) * (100-ISNULL(FSH.ISK2,0))/100) * (100-ISNULL(FSB.ALTISKORAN,0))/100)  AS TUTAR,
CASE WHEN  ISNULL(FSH.PERNO,0)<>0 THEN
(SELECT AD+'-'+SOYAD FROM TBLFASTERPERSONEL WHERE PERIND=FSH.PERNO)
ELSE
 (SELECT USERNAME FROM TBLUSERS WHERE IND=FSB.USERIND) END
 AS PERSONEL,
STK.MALINCINSI AS ProductName
  FROM TBLFASTERSATISHAREKET AS FSH
  LEFT JOIN TBLFASTERSATISBASLIK AS FSB ON FSH.BASLIKIND=FSB.BASLIKIND AND FSH.SUBEIND=FSB.SUBEIND AND FSH.KASAIND=FSB.KASAIND
  LEFT JOIN TBLFASTERSTOKLAR AS STK ON FSH.STOKIND=STK.IND
WHERE FSH.ISLEMTARIHI>=@Trh1 AND FSH.ISLEMTARIHI<=@Trh2 AND ISNULL(FSB.IADE,0)=0
GROUP BY FSB.SUBEIND,FSB.KASAIND,STK.MALINCINSI,FSH.PERNO,FSB.USERIND)  ) AS T
GROUP BY
T.SUBE1,
T.KASA,
T.PERSONEL