DECLARE @TRH1 AS DATETIME='{TARIH1}'
DECLARE @TRH2 AS DATETIME='{TARIH2}'
DECLARE @KOD1 NVARCHAR(100)='{KOD1}'
DECLARE @URUNADI AS NVARCHAR(100)='{URUNADI}'
DECLARE @SUBEADI AS NVARCHAR(100)='{SUBEADI}'

SELECT 
*,
(T.AdetMiktar/T.ToplamMiktar)*100 AS Oran

FROM (
SELECT 
KOD1,
SUM(Quantity*AGIRLIK)*10 as AdetMiktar,
sum(Quantity*Price) AS TUTAR,
(SELECT SUM(Quantity*AGIRLIK)*10 FROM [dbo].[Bill] AS HR WHERE KOD1=HR.KOD1 AND  Date>=@TRH1  AND Date<=@TRH2 and KOD1 LIKE '%DONER%'  #KOD1WHERE# #URUNADIWHERE# #TEKTRHWHERE# #SUBEADIWHERE# #BELÝRLÝSAATLER# #PORSIYONTIPIWHERE#) AS ToplamMiktar



 FROM [dbo].[Bill] AS HR WHERE Date>=@TRH1  AND Date<=@TRH2 and KOD1 LIKE '%DONER%'  #KOD1WHERE# #URUNADIWHERE# #TEKTRHWHERE# #SUBEADIWHERE# #BELÝRLÝSAATLER# #PORSIYONTIPIWHERE#
GROUP BY
KOD1
) AS T 