declare @par1 nvarchar(20) = '{TARIH1}';
declare @par2 nvarchar(20) = '{TARIH2}';
declare @Sube nvarchar(100) = '{SUBEADI}';
declare @Sube2 nvarchar(100) = '{SUBE2}';
declare @Kasa nvarchar(100) = '{KASAKODU}';
declare @ProductsName nvarchar(100) = '{ProductName}';

SELECT 
H.IND AS Id,B.OLUSTURMATARIHI Date,ISNULL(K.KODU,'')+'-'+ISNULL(K.ADI,'') UserName,H.STOKADI ProductName ,
H.STOKIND ProductId,0 Choice1Id,0 Choice2Id,'' Options,
SUM(MIKTAR*H.FIYAT) Price,SUM(H.MIKTAR) Quantity,'' Comment,0 HeaderId,0 OrderId 
	FROM TBLSPOSSATISHAREKET H WITH(NOLOCK)
	LEFT JOIN TBLSPOSSATISBASLIK B WITH(NOLOCK) ON B.IND=H.BASLIKIND
		LEFT JOIN TBLSPOSKULLANICILAR K WITH(NOLOCK) ON K.IND=B.KULLANICIIND
		
WHERE IADE=1 AND IPTAL=0 AND B.OLUSTURMATARIHI>=@par1 AND B.OLUSTURMATARIHI<=@par2
AND H.STOKADI=@ProductsName
AND SUBEIND IN (SELECT IND FROM TBLSPOSSUBELER  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND KODU=@Sube2)   
AND KASAIND IN (SELECT IND FROM TBLSPOSKASALAR  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND Charindex('&'+KODU+'&',@kasa)>0)
group by H.STOKADI,H.IND,B.OLUSTURMATARIHI,K.KODU,K.ADI,H.STOKADI,H.STOKIND

ORDER BY H.IND

