
declare @Trh1 nvarchar(20) = '{TARIH1}';
declare @Trh2 nvarchar(20) = '{TARIH2}';
declare @Sube nvarchar(100) = '{SUBEADI}';
declare @Sube2 nvarchar(100) = '{SUBE2}';
declare @Kasa nvarchar(100) = '{KASAKODU}';

SELECT 
 SUM(MIKTAR*FIYAT) AS ToplamIptalTutari,
 SUM(MIKTAR) as ToplamIptalMiktari 
FROM TBLSPOSSATISHAREKETLOG H WITH(NOLOCK)
LEFT JOIN TBLSPOSSATISBASLIKLOG B WITH(NOLOCK) ON B.IND=H.BASLIKIND
WHERE  B.IADE=0 AND B.IPTAL=0 AND B.OLUSTURMATARIHI>=@Trh1 AND B.OLUSTURMATARIHI<=@Trh2 
AND SUBEIND IN (SELECT IND FROM TBLSPOSSUBELER  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND KODU=@Sube2)   
AND KASAIND IN (SELECT IND FROM TBLSPOSKASALAR  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND Charindex('&'+KODU+'&',@kasa)>0)