
declare @Trh1 nvarchar(20) = '{TARIH1}';
declare @Trh2 nvarchar(20) = '{TARIH2}';
declare @Sube nvarchar(100) = '{SUBEADI}';
declare @Sube2 nvarchar(100) = '{SUBE2}';
declare @Kasa nvarchar(100) = '{KASAKODU}';

WITH 
iskonto as (SELECT 

  B.BELGENO TableNo, B.OLUSTURMATARIHI PaymentTime, ISNULL(K.KODU,'')+'-'+ISNULL(K.ADI,'') ReceivedByUserName,
 H.ACIKLAMA DiscountReason, 0 CashPayment,0 CreditPayment,0 TicketPayment,(H.ISKTUTARI)  AS Discount 
FROM TBLSPOSSATISHAREKET H WITH(NOLOCK)
LEFT JOIN TBLSPOSSATISBASLIK B WITH(NOLOCK) ON B.IND=H.BASLIKIND
	LEFT JOIN TBLSPOSKULLANICILAR K WITH(NOLOCK) ON K.IND=B.KULLANICIIND
WHERE ISKORANI1>0  AND IADE=0 AND B.IPTAL=0 AND B.OLUSTURMATARIHI>=@Trh1 AND B.OLUSTURMATARIHI<=@Trh2
AND SUBEIND IN (SELECT IND FROM TBLSPOSSUBELER  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND KODU=@Sube2)   
AND KASAIND IN (SELECT IND FROM TBLSPOSKASALAR  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND Charindex('&'+KODU+'&',@kasa)>0)

UNION ALL
SELECT 
  B.BELGENO TableNo, B.OLUSTURMATARIHI PaymentTime, ISNULL(K.KODU,'')+'-'+ISNULL(K.ADI,'') ReceivedByUserName,
 H.ACIKLAMA DiscountReason, 0 CashPayment,0 CreditPayment,0 TicketPayment,(H.ISKTUTARI)*-1  AS Discount 
FROM TBLSPOSSATISHAREKET H WITH(NOLOCK)
LEFT JOIN TBLSPOSSATISBASLIK B WITH(NOLOCK) ON B.IND=H.BASLIKIND
	LEFT JOIN TBLSPOSKULLANICILAR K WITH(NOLOCK) ON K.IND=B.KULLANICIIND
WHERE ISKORANI1>0 AND B.IADE=1 AND B.IPTAL=0 AND B.OLUSTURMATARIHI>=@Trh1 AND B.OLUSTURMATARIHI<=@Trh2
AND SUBEIND IN (SELECT IND FROM TBLSPOSSUBELER  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND KODU=@Sube2)   
AND KASAIND IN (SELECT IND FROM TBLSPOSKASALAR  WITH(NOLOCK) WHERE ISNULL(IsDeleted,0)=0 AND Charindex('&'+KODU+'&',@kasa)>0)
)

SELECT TableNo,PaymentTime,ReceivedByUserName,DiscountReason,CashPayment,CreditPayment,TicketPayment,Discount   FROM iskonto AS P 